FROM postgres:14
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=password

ENV POSTGRES_DB=database_containerization_PW4

COPY ./init.sql /docker-entrypoint-initdb.d/



ENV POSTGRES_DB=db_td4_containerization

